/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/123cc8c2-a24d-4e87-af09-e45637989f0c 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLuminance blue;
  CloudLuminance green;
  CloudLuminance red;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

const int esp_red = 16 ;
const int esp_green = 5 ;
const int esp_blue = 4 ; 

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  pinMode(red,OUTPUT) ;
  pinMode(green,OUTPUT) ;
  pinMode(blue,OUTPUT) ;
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  Serial.println("nothing") ;
}

/*
  Since Blue is READ_WRITE variable, onBlueChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBlueChange()  {
  // Add your code here to act upon Blue change
  analogWrite(esp_blue,blue) ;
}
/*
  Since Green is READ_WRITE variable, onGreenChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGreenChange()  {
  // Add your code here to act upon Green change
  analogWrite(esp_green,green) ;
}
/*
  Since Red is READ_WRITE variable, onRedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRedChange()  {
  // Add your code here to act upon Red change
  analogWrite(esp_red,red) ;
}







